"""
maven_install_glue — Bzlmod module extension.

Bridges the gap between the resolved artifact list (computed by
maven_wildcard_deps) and rules_jvm_external's maven_install().

Background on why this exists
──────────────────────────────
rules_jvm_external's Bzlmod extension requires static `maven.artifact()`
tags at MODULE.bazel evaluation time. We cannot feed it a dynamically
computed list. The solution is a thin repository_rule that:
  1. Reads the resolved.bzl from phase 1 at repository-rule evaluation time
     (which happens after module extensions, and CAN load dynamic content).
  2. Calls maven_install() with the computed list.

This is architecturally sound because:
  - module_extension runs first (determines the graph of repos)
  - repository_rules run lazily on demand
  - rules_jvm_external's maven_install IS a repository_rule under the hood

Limitation
──────────
This glue calls maven_install() from Starlark which requires
rules_jvm_external ≥ 5.0 (the version that exposed maven_install as a
standalone callable rather than only via WORKSPACE macros).
Bzlmod support requires rules_jvm_external ≥ 6.0.
"""

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

# ─── Repository rule ──────────────────────────────────────────────────────────

def _maven_install_from_resolved_impl(ctx):
    """
    Repository rule that:
      1. Loads resolved.bzl from the phase-1 repository.
      2. Calls maven_install() with the resolved artifact list.
      3. Produces a BUILD.bazel that re-exports the maven install target.
    """

    # Load the resolved artifact list from phase 1.
    # ctx.path() can resolve Label references to absolute paths.
    resolved_bzl_path = ctx.path(
        Label("@{}//:resolved.bzl".format(ctx.attr.resolved_repo_name))
    )

    # Read and exec the .bzl file to extract RESOLVED_ARTIFACTS etc.
    # Starlark has no exec/import — use python3 to extract the values.
    extract_py = """
import ast, sys, json

path = sys.argv[1]
src  = open(path).read()
tree = ast.parse(src)

result = {}
for node in tree.body:
    if isinstance(node, ast.Assign):
        for t in node.targets:
            if isinstance(t, ast.Name) and t.id in (
                "RESOLVED_ARTIFACTS", "RESOLVED_REPOSITORIES",
                "FETCH_SOURCES", "FETCH_JAVADOC"
            ):
                result[t.id] = ast.literal_eval(node.value)

print(json.dumps(result))
"""
    r = ctx.execute(
        ["python3", "-c", extract_py, str(resolved_bzl_path)],
        timeout = 30,
        quiet   = True,
    )
    if r.return_code != 0:
        fail("Failed to extract resolved artifacts: {}".format(r.stderr))

    import_result = json.decode(r.stdout.strip())

    artifacts    = import_result.get("RESOLVED_ARTIFACTS", [])
    repositories = import_result.get("RESOLVED_REPOSITORIES", ["https://repo1.maven.org/maven2/"])
    fetch_sources = import_result.get("FETCH_SOURCES", True)
    fetch_javadoc = import_result.get("FETCH_JAVADOC", False)

    if not artifacts:
        fail("RESOLVED_ARTIFACTS is empty in {}".format(str(resolved_bzl_path)))

    # Call maven_install() — this is a macro that creates the @maven repository
    # (or whatever name ctx.attr.maven_repo_name specifies).
    maven_install(
        name         = ctx.attr.maven_repo_name,
        artifacts    = artifacts,
        repositories = repositories,
        fetch_sources = fetch_sources,
        fetch_javadoc = fetch_javadoc,
        # Reproducible builds: resolve_timeout ensures we don't get
        # non-deterministic Coursier behaviour in CI.
        resolve_timeout = 600,
        # Fail on version conflict rather than silently picking one.
        # Remove if your dependency graph has known conflicts to mediate.
        strict_visibility = True,
    )

    ctx.file("BUILD.bazel", """# AUTO-GENERATED by maven_install_glue
# This repository exists only to trigger maven_install; targets live in @maven//...
""")

_maven_install_from_resolved_rule = repository_rule(
    implementation = _maven_install_from_resolved_impl,
    attrs = {
        "resolved_repo_name": attr.string(mandatory = True),
        "maven_repo_name":    attr.string(default = "maven"),
    },
    doc = "Loads a resolved Maven artifact list and calls maven_install().",
)

# ─── Tag class ────────────────────────────────────────────────────────────────

_install_tag = tag_class(
    attrs = {
        "resolved_repo": attr.string(
            mandatory = True,
            doc = (
                "Name of the repository produced by maven_wildcard_deps " +
                "that contains resolved.bzl. " +
                "Example: 'resolved_maven_deps_maven_deps_yaml'"
            ),
        ),
        "maven_repo_name": attr.string(
            default = "maven",
            doc = "Name of the @maven repository to create (default: 'maven').",
        ),
    },
)

# ─── Module extension ─────────────────────────────────────────────────────────

def _maven_install_from_resolved_impl_ext(mctx):
    rules_jvm_external_deps()

    for mod in mctx.modules:
        for tag in mod.tags.install:
            # Strip leading @ if present
            repo_name = tag.resolved_repo.lstrip("@")

            _maven_install_from_resolved_rule(
                name                = "maven_glue_trigger_{}".format(tag.maven_repo_name),
                resolved_repo_name  = repo_name,
                maven_repo_name     = tag.maven_repo_name,
            )

maven_install_from_resolved = module_extension(
    implementation = _maven_install_from_resolved_impl_ext,
    tag_classes    = {"install": _install_tag},
    doc = (
        "Loads resolved Maven artifacts from a phase-1 repository and " +
        "wires them into rules_jvm_external's maven_install()."
    ),
)
